config/routes.rb
Eventmanager::Application.routes.draw do
  resources :memberships

  resources :mailgroups

  resources :prospects

  root :to => "prospects#index"

end

app/models/mailgroup.rb
class Mailgroup < ActiveRecord::Base
  has_many :memberships
  has_many :prospects, :through => :memberships
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :mailgroup
  belongs_to :prospect
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
  has_many :memberships
  has_many :mailgroups, :through => :memberships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mailgroups_controller.rb
class MailgroupsController < ApplicationController
  # GET /mailgroups
  # GET /mailgroups.xml
  def index
    @mailgroups = Mailgroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mailgroups }
    end
  end

  # GET /mailgroups/1
  # GET /mailgroups/1.xml
  def show
    @mailgroup = Mailgroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mailgroup }
    end
  end

  # GET /mailgroups/new
  # GET /mailgroups/new.xml
  def new
    @mailgroup = Mailgroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mailgroup }
    end
  end

  # GET /mailgroups/1/edit
  def edit
    @mailgroup = Mailgroup.find(params[:id])
  end

  # POST /mailgroups
  # POST /mailgroups.xml
  def create
    @mailgroup = Mailgroup.new(params[:mailgroup])

    respond_to do |format|
      if @mailgroup.save
        format.html { redirect_to(@mailgroup, :notice => 'Mailgroup was successfully created.') }
        format.xml  { render :xml => @mailgroup, :status => :created, :location => @mailgroup }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mailgroup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mailgroups/1
  # PUT /mailgroups/1.xml
  def update
    @mailgroup = Mailgroup.find(params[:id])

    respond_to do |format|
      if @mailgroup.update_attributes(params[:mailgroup])
        format.html { redirect_to(@mailgroup, :notice => 'Mailgroup was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mailgroup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mailgroups/1
  # DELETE /mailgroups/1.xml
  def destroy
    @mailgroup = Mailgroup.find(params[:id])
    @mailgroup.destroy

    respond_to do |format|
      format.html { redirect_to(mailgroups_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  # GET /memberships
  # GET /memberships.xml
  def index
    @memberships = Membership.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @memberships }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.xml
  def show
    @membership = Membership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @membership }
    end
  end

  # GET /memberships/new
  # GET /memberships/new.xml
  def new
    @membership = Membership.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @membership }
    end
  end

  # GET /memberships/1/edit
  def edit
    @membership = Membership.find(params[:id])
  end

  # POST /memberships
  # POST /memberships.xml
  def create
    @membership = Membership.new(params[:membership])

    respond_to do |format|
      if @membership.save
        format.html { redirect_to(@membership, :notice => 'Membership was successfully created.') }
        format.xml  { render :xml => @membership, :status => :created, :location => @membership }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @membership.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /memberships/1
  # PUT /memberships/1.xml
  def update
    @membership = Membership.find(params[:id])

    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        format.html { redirect_to(@membership, :notice => 'Membership was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @membership.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.xml
  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to(memberships_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  # GET /prospects
  # GET /prospects.xml
  def index
    @prospects = Prospect.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @prospects }
    end
  end

  # GET /prospects/1
  # GET /prospects/1.xml
  def show
    @prospect = Prospect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @prospect }
    end
  end

  # GET /prospects/new
  # GET /prospects/new.xml
  def new
    @prospect = Prospect.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @prospect }
    end
  end

  # GET /prospects/1/edit
  def edit
    @prospect = Prospect.find(params[:id])
  end

  # POST /prospects
  # POST /prospects.xml
  def create
    @prospect = Prospect.new(params[:prospect])

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to(@prospect, :notice => 'Prospect was successfully created.') }
        format.xml  { render :xml => @prospect, :status => :created, :location => @prospect }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @prospect.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /prospects/1
  # PUT /prospects/1.xml
  def update
    @prospect = Prospect.find(params[:id])

    respond_to do |format|
      if @prospect.update_attributes(params[:prospect])
        format.html { redirect_to(@prospect, :notice => 'Prospect was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @prospect.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.xml
  def destroy
    @prospect = Prospect.find(params[:id])
    @prospect.destroy

    respond_to do |format|
      format.html { redirect_to(prospects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mailgroups_helper.rb
module MailgroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventmanager</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mailgroups/_form.html.erb
<%= form_for(@mailgroup) do |f| %>
  <% if @mailgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mailgroup.errors.count, "error") %> prohibited this mailgroup from being saved:</h2>

      <ul>
      <% @mailgroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mailgroups/edit.html.erb
<h1>Editing mailgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @mailgroup %> |
<%= link_to 'Back', mailgroups_path %>

app/views/mailgroups/index.html.erb
<h1>Listing mailgroups</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mailgroups.each do |mailgroup| %>
  <tr>
    <td><%= mailgroup.name %></td>
    <td><%= link_to 'Show', mailgroup %></td>
    <td><%= link_to 'Edit', edit_mailgroup_path(mailgroup) %></td>
    <td><%= link_to 'Destroy', mailgroup, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mailgroup', new_mailgroup_path %>

app/views/mailgroups/new.html.erb
<h1>New mailgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', mailgroups_path %>

app/views/mailgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mailgroup.name %>
</p>


<%= link_to 'Edit', edit_mailgroup_path(@mailgroup) %> |
<%= link_to 'Back', mailgroups_path %>

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prospect_id %><br />
    <%= f.text_field :prospect_id %>
  </div>
  <div class="field">
    <%= f.label :mailgroup_id %><br />
    <%= f.text_field :mailgroup_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing memberships</h1>

<table>
  <tr>
    <th>Prospect</th>
    <th>Mailgroup</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memberships.each do |membership| %>
  <tr>
    <td><%= membership.prospect_id %></td>
    <td><%= membership.mailgroup_id %></td>
    <td><%= link_to 'Show', membership %></td>
    <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
    <td><%= link_to 'Destroy', membership, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Prospect:</b>
  <%= @membership.prospect_id %>
</p>

<p>
  <b>Mailgroup:</b>
  <%= @membership.mailgroup_id %>
</p>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>

app/views/prospects/_form.html.erb
<%= form_for(@prospect) do |f| %>
  <% if @prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
      <% @prospect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :weddingDate %><br />
    <%= f.date_select :weddingDate, {:include_blank => true, :default => nil, :order => [:month, :day, :year], :start_year => 2011} %>
  </div>
  <div class="field">
    <%= f.label :referral %><br />
    <%= f.text_field :referral %>
  </div>
  <div class="field">
    <%= f.label :firstContact %><br />
    <%= f.date_select :firstContact, {:include_blank => true, :default => nil, :order => [:month, :day, :year], :start_year => 2011} %>
  </div>
  <div class="field">
    <%= f.label :booked %><br />
    <%= f.check_box :booked %>
  </div>
  <div class="field">
    <%= f.label :responded %><br />
    <%= f.check_box :responded %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="field">
    <%= f.label :mailgroups %><br />
    <%= f.select :mailgroups, @prospect.mailgroups.collect {|mailgroup| [mailgroup.name, mailgroup.id ] } %>
  </div>
<% end %>

app/views/prospects/edit.html.erb
<h1>Editing prospect</h1>

<%= render 'form' %>

<%= link_to 'Show', @prospect %> |
<%= link_to 'Back', prospects_path %>

app/views/prospects/index.html.erb
<h1>Listing prospects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Weddingdate</th>
    <th>Referral</th>
    <th>Responded</th>
    <th>Firstcontact</th>
    <th>Booked</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prospects.each do |prospect| %>
  <tr>
    <td><%= prospect.name %></td>
    <td><%= prospect.email %></td>
    <td><%= prospect.weddingDate %></td>
    <td><%= prospect.referral %></td>
    <td><%= prospect.responded %></td>
    <td><%= prospect.firstContact %></td>
    <td><%= prospect.booked %></td>
    <td><%= prospect.notes %></td>
    <td><%= link_to 'Show', prospect %></td>
    <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
    <td><%= link_to 'Destroy', prospect, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prospect', new_prospect_path %>

app/views/prospects/new.html.erb
<h1>New prospect</h1>

<%= render 'form' %>

<%= link_to 'Back', prospects_path %>

app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @prospect.name %>
</p>

<p>
  <b>Email:</b>
  <%= @prospect.email %>
</p>

<p>
  <b>Weddingdate:</b>
  <%= @prospect.weddingDate %>
</p>

<p>
  <b>Referral:</b>
  <%= @prospect.referral %>
</p>

<p>
  <b>Firstcontact:</b>
  <%= @prospect.firstContact %>
</p>

<p>
  <b>Booked:</b>
  <%= @prospect.booked %>
</p>

<p>
  <b>Responded:</b>
  <%= @prospect.responded %>
</p>

<p>
  <b>Notes:</b>
  <%= @prospect.notes %>
</p>


<%= link_to 'Edit', edit_prospect_path(@prospect) %> |
<%= link_to 'Back', prospects_path %>

app/views/reminder/email.text.erb
Welcome to example.com, <%= @user.name %>
===============================================
 
You have successfully signed up to example.com,
your username is: <%= @user.login %>.
 
To login to the site, just follow this link: <%= @url %>.
 
Thanks for joining and have a great day!

app/views/reminder/welcome_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h1>Welcome to example.com, <%= @prospect.name %></h1>
    <p>
      You have successfully signed up to example.com,
      your username is: <%= @prospect.name %>.<br/>
    </p>
    <p>
      To login to the site, just follow this link: <%= @url %>.
    </p>
    <p>Thanks for joining and have a great day!</p>
  </body>
</html>